# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContactMethod(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, label: str=None, contact_details: str=None, user: str=None, uuid: str=None):  # noqa: E501
        """ContactMethod - a model defined in Swagger

        :param label: The label of this ContactMethod.  # noqa: E501
        :type label: str
        :param contact_details: The contact_details of this ContactMethod.  # noqa: E501
        :type contact_details: str
        :param user: The user of this ContactMethod.  # noqa: E501
        :type user: str
        :param uuid: The uuid of this ContactMethod.  # noqa: E501
        :type uuid: str
        """
        self.swagger_types = {
            'label': str,
            'contact_details': str,
            'user': str,
            'uuid': str
        }

        self.attribute_map = {
            'label': 'label',
            'contact_details': 'contactDetails',
            'user': 'user',
            'uuid': 'uuid'
        }

        self._label = label
        self._contact_details = contact_details
        self._user = user
        self._uuid = uuid

    @classmethod
    def from_dict(cls, dikt) -> 'ContactMethod':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ContactMethod of this ContactMethod.  # noqa: E501
        :rtype: ContactMethod
        """
        return util.deserialize_model(dikt, cls)

    @property
    def label(self) -> str:
        """Gets the label of this ContactMethod.


        :return: The label of this ContactMethod.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this ContactMethod.


        :param label: The label of this ContactMethod.
        :type label: str
        """

        self._label = label

    @property
    def contact_details(self) -> str:
        """Gets the contact_details of this ContactMethod.


        :return: The contact_details of this ContactMethod.
        :rtype: str
        """
        return self._contact_details

    @contact_details.setter
    def contact_details(self, contact_details: str):
        """Sets the contact_details of this ContactMethod.


        :param contact_details: The contact_details of this ContactMethod.
        :type contact_details: str
        """

        self._contact_details = contact_details

    @property
    def user(self) -> str:
        """Gets the user of this ContactMethod.


        :return: The user of this ContactMethod.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this ContactMethod.


        :param user: The user of this ContactMethod.
        :type user: str
        """

        self._user = user

    @property
    def uuid(self) -> str:
        """Gets the uuid of this ContactMethod.


        :return: The uuid of this ContactMethod.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this ContactMethod.


        :param uuid: The uuid of this ContactMethod.
        :type uuid: str
        """

        self._uuid = uuid
