# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QuestionIn(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, question: str=None, church: str=None):  # noqa: E501
        """QuestionIn - a model defined in Swagger

        :param question: The question of this QuestionIn.  # noqa: E501
        :type question: str
        :param church: The church of this QuestionIn.  # noqa: E501
        :type church: str
        """
        self.swagger_types = {
            'question': str,
            'church': str
        }

        self.attribute_map = {
            'question': 'question',
            'church': 'church'
        }

        self._question = question
        self._church = church

    @classmethod
    def from_dict(cls, dikt) -> 'QuestionIn':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QuestionIn of this QuestionIn.  # noqa: E501
        :rtype: QuestionIn
        """
        return util.deserialize_model(dikt, cls)

    @property
    def question(self) -> str:
        """Gets the question of this QuestionIn.


        :return: The question of this QuestionIn.
        :rtype: str
        """
        return self._question

    @question.setter
    def question(self, question: str):
        """Sets the question of this QuestionIn.


        :param question: The question of this QuestionIn.
        :type question: str
        """

        self._question = question

    @property
    def church(self) -> str:
        """Gets the church of this QuestionIn.


        :return: The church of this QuestionIn.
        :rtype: str
        """
        return self._church

    @church.setter
    def church(self, church: str):
        """Sets the church of this QuestionIn.


        :param church: The church of this QuestionIn.
        :type church: str
        """

        self._church = church
